ユーザーフォローの課題
siroemk/fjord-books_app pull request #7
Opened 2021-09-10 05:37 UTC by siroemk

ユーザーフォローの機能を追加しました。
rubocop通過済みです。ご確認をお願いします。

2021-09-15 15:08 UTC, komagata requested changes

2021-09-15 15:08 UTC, komagata commented on app/controllers/users_controller.rb
> +  def followings
書きの参考にある[DHHはどのようにRailsのコントローラを書くのか](https://postd.cc/how-dhh-organizes-his-rails-controllers/)を参考にして、ControllerにCRUD以外のメソッドを作らずに作ってみてください〜

[Railsでユーザーフォローを作る | FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/170)

2021-09-19 02:22 UTC, siroemk commented
@komagata 
「コントローラにCRUD以外のメソッドを作らない」という意味が分かっていなかったので、もう一度調べ直して、やっと理解できました。ありがとうございます！

users_controller.rbの中身followersコントローラとfollowingsコントローラに分けてみました。
ご確認をお願いします。

2021-09-19 05:43 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-22 00:53 UTC, merged