テストの課題
siroemk/fjord-books_app pull request #9
Opened 2021-10-21 08:21 UTC by siroemk

booksアプリのテストを書きました。
rubocop通過済みです。ご確認をお願いします。

以下のテストを書いています。
- ReportクラスとUserクラスのインスタンスメソッドに対してモデルテストを書く
- メールアドレスとパスワードでログインして日報を書く、という一連の流れをシステムテストで書く
- 日報の編集や日報の削除のテストコードを書く
- 本の登録、編集や削除のテストコードを書く

2021-10-26 01:27 UTC, komagata requested changes

2021-10-26 01:27 UTC, komagata commented on test/fixtures/relationships.yml
> +#one:
gitで管理しているのでいつでも昔のコードを取り出して戻すことができます。

ですのでコメントアウトして古いコードを残しておくというのは基本的にやらないので、不要なコード・ファイルであれば削除するようにしちゃってください〜

2021-10-26 08:36 UTC, siroemk commented
@komagata 
ご確認いただき、ありがとうございました！
コメントアウトしていた不要なコードを削除しました。
よろしくお願いします。

2021-10-27 03:05 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-10-28 02:17 UTC, merged